"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { DocumentExplanation, explainDocument } from "../lib/api";
import { Language, localized, withLanguage } from "../lib/i18n";

const copy = {
  ko: { title: "어려운 문서를 쉽게 이해하세요", desc: "행정·노동 문서의 핵심 내용과 해야 할 일을 정리해 드려요.", choose: "PDF, 이미지 또는 텍스트 파일 선택", consent: "스캔 PDF·이미지는 개인정보를 포함한 원본이 AI 분석을 위해 일시 전송될 수 있음을 확인했습니다.", submit: "문서 설명하기", summary: "쉬운 설명", points: "핵심 내용", actions: "해야 할 일", deadlines: "확인된 기한", cautions: "주의사항", guides: "관련 가이드", again: "다른 문서 확인", redacted: "텍스트 개인정보가 자동 마스킹되었습니다." },
  en: { title: "Understand difficult documents", desc: "Get a plain-language summary and a list of actions.", choose: "Choose a PDF, image, or text file", consent: "I understand that scanned PDFs or images may be sent temporarily for AI analysis with personal data visible.", submit: "Explain document", summary: "Plain summary", points: "Key points", actions: "What to do", deadlines: "Deadlines found", cautions: "Cautions", guides: "Related guides", again: "Check another document", redacted: "Personal data in extracted text was redacted." },
  vi: { title: "Hiểu tài liệu khó một cách dễ dàng", desc: "Xem tóm tắt dễ hiểu và những việc cần làm.", choose: "Chọn PDF, ảnh hoặc tệp văn bản", consent: "Tôi hiểu rằng PDF quét hoặc ảnh có thể được gửi tạm thời để AI phân tích khi còn hiển thị dữ liệu cá nhân.", submit: "Giải thích tài liệu", summary: "Giải thích dễ hiểu", points: "Nội dung chính", actions: "Việc cần làm", deadlines: "Thời hạn", cautions: "Lưu ý", guides: "Hướng dẫn liên quan", again: "Xem tài liệu khác", redacted: "Dữ liệu cá nhân trong văn bản đã được che." },
} as const;

export function DocumentClient({ language }: { language: Language }) {
  const t = copy[language];
  const [file, setFile] = useState<File | null>(null); const [consent, setConsent] = useState(false); const [result, setResult] = useState<DocumentExplanation | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const needsConsent = !!file && file.type !== "text/plain";
  async function submit(event: FormEvent) { event.preventDefault(); if (!file || (needsConsent && !consent)) return; setLoading(true); setError(""); try { setResult(await explainDocument(file, language, consent)); } catch { setError("문서를 처리할 수 없습니다. 파일과 API 설정을 확인해 주세요. / Unable to process the document."); } finally { setLoading(false); } }
  return <section className="document-shell content-width"><header className="document-heading"><div className="eyebrow">DOCUMENT EXPLAINER</div><h1>{t.title}</h1><p>{t.desc}</p></header>{!result ? <form className="document-upload" onSubmit={submit}><label className="file-drop"><input type="file" accept=".pdf,.txt,image/png,image/jpeg,image/webp" onChange={(event) => { setFile(event.target.files?.[0] || null); setConsent(false); }} /><span>📄</span><strong>{file?.name || t.choose}</strong><small>PDF · PNG · JPG · WEBP · TXT · max 5MB</small></label>{needsConsent && <label className="consent"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span>{t.consent}</span></label>}{error && <p className="inline-error">{error}</p>}<button className="primary chat-submit" disabled={!file || loading || (needsConsent && !consent)}>{loading ? "…" : t.submit}</button></form> : <div className="document-results">{result.privacy_redacted && <div className="privacy-note">🔒 {t.redacted}</div>}<ResultSection title={t.summary} items={[result.summary]} /><ResultSection title={t.points} items={result.key_points} /><ResultSection title={t.actions} items={result.actions} numbered /><ResultSection title={t.deadlines} items={result.deadlines} /><ResultSection title={t.cautions} items={result.cautions} caution />{result.related_guides.length > 0 && <section className="document-result-card"><h2>{t.guides}</h2>{result.related_guides.map((guide) => <Link className="document-guide" href={withLanguage(`/guides/${guide.id}`, language)} key={guide.id}>{localized(guide.title, language)} <b>→</b></Link>)}</section>}<button className="secondary reset-button" onClick={() => { setResult(null); setFile(null); }}>{t.again}</button></div>}</section>;
}

function ResultSection({ title, items, numbered, caution }: { title: string; items: string[]; numbered?: boolean; caution?: boolean }) { if (!items.length) return null; const List = numbered ? "ol" : "ul"; return <section className={`document-result-card ${caution ? "caution" : ""}`}><h2>{title}</h2><List>{items.map((item) => <li key={item}>{item}</li>)}</List></section>; }
